version: '3.9'

services:
  web:
    build: .
    container_name: django_shop
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: shop_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  postgres_data:
